"""
Migration 005 - Resize policy_chunks.embedding from vector(384) to vector(768).
The embedding column was created as vector(384) (matching sentence-transformers
all-MiniLM-L6-v2). The deployment now uses Ollama nomic-embed-text:latest which
produces 768-dimensional vectors. This migration:
  1. Drops all existing policy_chunk rows (they carry stale 384-dim embeddings
     that cannot be compared with 768-dim query vectors).
  2. Alters the column type from vector(384) to vector(768).
Policy chunks will be re-seeded by running scripts/ingest_policies.py after
this migration is applied.
Revision ID: 005
Revises: 004
Create Date: 2026-09-27
"""
from __future__ import annotations
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # Step 1: Clear all existing embeddings (they are 384-dim; incompatible with
    # the 768-dim model now in use). Policy chunks are purely derived data and can
    # be regenerated by running scripts/ingest_policies.py.
    op.execute("DELETE FROM policy_chunks")
    # Step 2: PostgreSQL pgvector does not support ALTER COLUMN TYPE directly on
    # a vector column. We must drop and recreate the column.
    op.drop_column("policy_chunks", "embedding")
    op.add_column(
        "policy_chunks",
        sa.Column("embedding", sa.Text(), nullable=True),  # placeholder type
    )
    # Step 3: Use raw SQL to set the correct pgvector type.
    op.execute("ALTER TABLE policy_chunks ALTER COLUMN embedding TYPE vector(768) USING NULL")
def downgrade() -> None:
    op.execute("DELETE FROM policy_chunks")
    op.drop_column("policy_chunks", "embedding")
    op.add_column(
        "policy_chunks",
        sa.Column("embedding", sa.Text(), nullable=True),
    )
    op.execute("ALTER TABLE policy_chunks ALTER COLUMN embedding TYPE vector(384) USING NULL")